Final Project/Controllers/VideoLibraryController.cs
using Final_Project.DataContexts;
using Final_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Final_Project.Controllers
{
    public class VideoLibraryController : Controller
    {
        VideoDb videoDb = new VideoDb();

        //
        // GET: /VideoLibrary/
        public ActionResult Index()
        {
            //Video Library Controller Index Page (Category)
            //var cats = new List<Category>
            //{
            //    new Category { Name = "Gaming"},
            //    new Category { Name = "Comedy"},
            //    new Category { Name = "Music"},
            //    new Category { Name = "Autos and Vehicle"},
            //    new Category { Name = "Education"},
            //    new Category { Name = "Film and Animation"},
            //    new Category { Name = "News and Politics"},
            //    new Category { Name = "People and Blogs"},
            //    new Category { Name = "Sports"},
            //    new Category { Name = "Science and Technology"},
            //    new Category { Name = "Pets and Animals"}
            //};
            var cats = videoDb.Categories.ToList();

            return View(cats);
        }

        // GET: /VideoLibrary/Browse?category=gaming
        public ActionResult Browse(String category)
        {
            //Video Library Controller Browse Page
            //string cat = HttpUtility.HtmlEncode("VideoLibrary.Browse, Category = " + category);
            //cat Model for searching by category
            var catModel = videoDb.Categories.Include("Videos").Single(g => g.Name == category);

            return View(catModel);
        }

        public ActionResult v(int id)
        {

            int width = 750;
            int height = width * 9 / 16; // 16 : 9 ratio  

            //Video Library Controller Details Page
            //string details = "VideoLibrary.Details, ID = " + id;
            //var video = new Video { Title = "Video " + id };
            ViewBag.Width = width;
            ViewBag.Height = height;
            var video = videoDb.Videos.Find(id);
            return View(video);
        }
	}
}

Final Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title : Video Stage</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Video Stage", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Video Library", "Index", "VideoLibrary")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        @*<footer>
            <p>&copy; @DateTime.Now.Year : Video Stage</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>